<?php // prevent newrelic injected JavaScript breaking JSON
 if(extension_loaded(base64_decode('bmV3cmVsaWM='))){newrelic_disable_autorum();}include(base64_decode('Li4vLi4vLi4vd3AtbG9hZC5waHA='));//include_once("libs/errors.php");
 ini_set(base64_decode('ZGlzcGxheV9lcnJvcnM='),1);error_reporting(1);if(!function_exists(base64_decode('ZmlsZV9nZXRfaHRtbA=='))){require_once(base64_decode('bGlicy9zaW1wbGVfaHRtbF9kb20ucGhw'));}//include_once("libs/ml_content_redirect.php");
 include_once(base64_decode('Y2F0ZWdvcmllcy5waHA='));include_once(base64_decode('ZmlsdGVycy5waHA='));$hrw_0=false;/*** POSTS LIST ***/ $nij_1=$_POST[base64_decode('b2Zmc2V0')];$vab_2=$_POST[base64_decode('cG9zdGNvdW50')];$vio_3=$_POST[base64_decode('Y2F0ZWdvcnk=')];$yrb_4=$_POST[base64_decode('Y2F0ZWdvcnlfaWQ=')];/* If we didn't get a category ID, but got a category permalink, set the category ID, if we can get it */ if(empty($yrb_4)&&isset($_POST[base64_decode('cGVybWFsaW5r')])){$zwu_5=$_POST[base64_decode('cGVybWFsaW5r')];$adx_6=get_category_by_path($zwu_5,false);// So is it a category? Let's also tell the permalink parser we already figured it out
 if($adx_6){$yrb_4=$adx_6->$srl_7;$hrw_0=true;$zdk_8=$adx_6->$bld_9;}}$eue_a=$_POST[base64_decode('Y2F0ZWdvcmllcw==')];$dts_b=$_POST[base64_decode('c2VhcmNo')];$fmk_c=$_POST[base64_decode('YXBwX3ZlcnNpb24=')];$uuc_d=15;if(isset($_POST[base64_decode('bGltaXQ=')])){$uuc_d=$_POST[base64_decode('bGltaXQ=')];if($uuc_d>30)$uuc_d=30;}// Process the permalink parameter, unless we already did as a taxonomy
 if(isset($_POST[base64_decode('cGVybWFsaW5r')])&&!$hrw_0){$gqw_e=url_to_postid($_POST[base64_decode('cGVybWFsaW5r')]);if($gqw_e){$_POST[base64_decode('cG9zdF9pZA==')]=$gqw_e;}else{return;}}$dvi_f=explode(base64_decode('LA=='),get_option(base64_decode('bWxfYXJ0aWNsZV9saXN0X2luY2x1ZGVfcG9zdF90eXBlcw=='),base64_decode('cG9zdA==')));$gid_10=0;foreach($dvi_fas $dge_11){$gid_10+=wp_count_posts($dge_11)->$hbz_12;}$zwv_13=array();if($yrb_4){$zwv_13=ml_get_term_by(base64_decode('aWQ='),$yrb_4);$mpu_14=$zwv_13[base64_decode('dGVybQ==')];}else if($vio_3){$zwv_13=ml_get_term_by(base64_decode('c2x1Zw=='),$vio_3);$mpu_14=$zwv_13[base64_decode('dGVybQ==')];}if($mpu_14){$gid_10=get_post_count(array($mpu_14->$srl_7));$gid_10+=ml_get_category_child_post_count($mpu_14->$srl_7,$zwv_13[base64_decode('dGF4')]);}if($eue_a){$zou_15=array();$cbp_16=explode(base64_decode('LA=='),$eue_a);foreach($cbp_16as $ekl_17){$emq_18=get_category_by_slug($ekl_17);if(!$emq_18){$emq_18=get_category($ekl_17);}if($emq_18){array_push($zou_15,$emq_18->$rml_19);}}$gid_10=get_post_count($zou_15);}if($nij_1==NULL)$nij_1=0;if($vab_2==NULL)$vab_2=$gid_10;$wxb_1a=$gid_10-$vab_2;$xqh_1b=$nij_1+$wxb_1a;//not cached
 $dvi_f=explode(base64_decode('LA=='),get_option(base64_decode('bWxfYXJ0aWNsZV9saXN0X2luY2x1ZGVfcG9zdF90eXBlcw==')));$syo_1c=array();$xky_1d=array();$xmw_1e=array();$asl_1f='';if($vio_3){array_push($syo_1c,$vio_3);$rbu_20=$mpu_14;$asl_1f=$rbu_20->$srl_7;}else if($yrb_4){$rbu_20=$mpu_14;array_push($syo_1c,$rbu_20->$hbc_21);$asl_1f=$rbu_20->$srl_7;}else{$rjg_22=get_categories(base64_decode('b3JkZXJieT1uYW1l'));if(!empty($rjg_22)){$cee_23=explode(base64_decode('LA=='),get_option(base64_decode('bWxfYXJ0aWNsZV9saXN0X2V4Y2x1ZGVfY2F0ZWdvcmllcw=='),''));foreach($rjg_22as $hki_24){if(array_search($hki_24->$kbn_25,$cee_23)===false){$xmw_1e[$hki_24->$rml_19]=$hki_24->$rml_19;}}}}if(strlen($dts_b)>0 &&!in_array(base64_decode('cGFnZQ=='),$dvi_f)&&(get_option(base64_decode('bWxfaW5jbHVkZV9wYWdlc19pbl9zZWFyY2g='),base64_decode('ZmFsc2U='))==base64_decode('dHJ1ZQ==') ||get_option(base64_decode('bWxfaW5jbHVkZV9wYWdlc19pbl9zZWFyY2g='),base64_decode('ZmFsc2U='))==true)){array_push($dvi_f,base64_decode('cGFnZQ=='));}//echo('post types ' . json_encode($includedPostTypes) . ' ..');
 if((empty($dvi_f)||(isset($dvi_f[0])&&$dvi_f[0]==''))&&!(count($zwv_13)&&$zwv_13[base64_decode('dGVybQ==')])){return;}$dpi_26=array(base64_decode('cG9zdHNfcGVyX3BhZ2U=') =>$uuc_d,base64_decode('b3JkZXJieQ==') =>base64_decode('cG9zdF9kYXRl'),base64_decode('b3JkZXI=') =>base64_decode('REVTQw=='),base64_decode('cG9zdF90eXBl') =>$dvi_f,base64_decode('cG9zdF9zdGF0dXM=') =>base64_decode('cHVibGlzaA=='),base64_decode('b2Zmc2V0') =>$xqh_1b,base64_decode('cw==') =>$dts_b);if(count($zwv_13)&&$zwv_13[base64_decode('dGVybQ==')]){unset($dpi_26[base64_decode('cG9zdF90eXBl')]);}if(!empty($xmw_1e)){$dpi_26[base64_decode('Y2F0')]=implode(base64_decode('LA=='),$xmw_1e);}$zou_15=array();if(isset($_POST[base64_decode('Y2F0ZWdvcmllcw==')])){$zou_15=array();$cbp_16=explode(base64_decode('LA=='),$eue_a);foreach($cbp_16as $ekl_17){$emq_18=get_category_by_slug($ekl_17);if(!$emq_18){$emq_18=get_category($ekl_17);}if($emq_18){array_push($zou_15,$emq_18->$hbc_21);}}$qbe_27=implode(base64_decode('LA=='),$zou_15);$dpi_26[base64_decode('Y2F0ZWdvcnlfbmFtZQ==')]=$qbe_27;}else if(count($zwv_13)&&$zwv_13[base64_decode('dGVybQ==')]){$dpi_26[base64_decode('dGF4X3F1ZXJ5')]=array(array(base64_decode('dGF4b25vbXk=') =>$zwv_13[base64_decode('dGF4')],base64_decode('ZmllbGQ=') =>base64_decode('dGVybV9pZA=='),base64_decode('dGVybXM=') =>$zwv_13[base64_decode('dGVybQ==')]->$srl_7));}//echo json_encode($query_array);
 $ssd_28=array();if(!isset($_POST[base64_decode('cG9zdF9pZA==')])){$vcb_29=get_posts($dpi_26);$ssd_28=array();if($vio_3==NULL){$ulg_2a=get_option(base64_decode('c3RpY2t5X2NhdGVnb3J5XzE='));$xik_2b=get_option(base64_decode('c3RpY2t5X2NhdGVnb3J5XzI='));}//wp_reset_postdata();
 //must be the second, first because the first will be prepended
 if($xik_2b&&($xqh_1b==NULL ||$xqh_1b==0)){//loading second 3 posts of the sticky category
 $hki_24=ml_get_category($xik_2b);if($hki_24){$dpi_26[base64_decode('cG9zdHNfcGVyX3BhZ2U=')]=get_option(base64_decode('bWxfc3RpY2t5X2NhdGVnb3J5XzJfcG9zdHM='),3);$dpi_26[base64_decode('Y2F0ZWdvcnlfbmFtZQ==')]=null;$dpi_26[base64_decode('Y2F0ZWdvcnk=')]=null;$dpi_26[base64_decode('Y2F0')]=$hki_24->$rml_19;$dmg_2c=get_posts($dpi_26);foreach($dmg_2cas $aqt_2d){$aqt_2d->$syg_2e=true;foreach($vcb_29as $vim_2f=>$fgs_30){if($fgs_30->$zmr_31 ==$aqt_2d->$zmr_31)array_splice($vcb_29,$vim_2f,1);}}$vcb_29=array_merge($dmg_2c,$vcb_29);//wp_reset_postdata();
}}if($ulg_2a&&($xqh_1b==NULL ||$xqh_1b==0)){//loading first 3 posts of the sticky category
 $hki_24=get_category($ulg_2a);if($hki_24){$dpi_26[base64_decode('cG9zdHNfcGVyX3BhZ2U=')]=get_option(base64_decode('bWxfc3RpY2t5X2NhdGVnb3J5XzFfcG9zdHM='),3);;$dpi_26[base64_decode('Y2F0ZWdvcnlfbmFtZQ==')]=null;$dpi_26[base64_decode('Y2F0ZWdvcnk=')]=null;$dpi_26[base64_decode('Y2F0')]=$hki_24->$rml_19;$wuv_32=get_posts($dpi_26);foreach($wuv_32as $aqt_2d){$aqt_2d->$syg_2e=true;foreach($vcb_29as $vim_2f=>$fgs_30){if($fgs_30->$zmr_31 ==$aqt_2d->$zmr_31)array_splice($vcb_29,$vim_2f,1);}}$vcb_29=array_merge($wuv_32,$vcb_29);//wp_reset_postdata();
}}}else{$fva_33=$_POST[base64_decode('cG9zdF9pZA==')];$vcb_29=array();$vcb_29[0]=get_post($fva_33);}//subscriptions system enabled?
if(ml_subscriptions_enable()){//user login using
 //$_POST['username']
 //$_POST['password']
 $ngy_34=ml_login_wordpress($_POST[base64_decode('dXNlcm5hbWU=')],$_POST[base64_decode('cGFzc3dvcmQ=')]);if(get_class($ngy_34)==base64_decode('V1BfVXNlcg==')){//loggedin
 //subscriptions: filter posts using capabilities
 $vcb_29=ml_subscriptions_filter_posts($vcb_29,$ngy_34->$zmr_31);}else{$vcb_29=ml_subscriptions_filter_posts($vcb_29,null);}}print_posts($vcb_29,$gid_10,$nij_1,$ssd_28,$zdk_8,$hrw_0);function print_posts($vcb_29,$rua_35,$oba_36,$omv_37,$zdk_8,$hrw_0){/** JSON OUTPUT **/ $lrz_38=array(base64_decode('cG9zdHM=') =>array(),base64_decode('cG9zdC1jb3VudA==') =>$rua_35);$tnp_39=isset($_POST[base64_decode('YWxsb3dfbGF6eQ==')])?$_POST[base64_decode('YWxsb3dfbGF6eQ==')]:false;foreach($vcb_29as $sst_3a){$cpf_3b=$sst_3a->$zmr_31;if($oba_36>0 &&is_sticky($cpf_3b))continue;/** comments **/ $acf_3c=get_children(array(base64_decode('cG9zdF9wYXJlbnQ=') =>$cpf_3b,base64_decode('cG9zdF90eXBl') =>base64_decode('YXR0YWNobWVudA=='),base64_decode('cG9zdF9taW1lX3R5cGU=') =>base64_decode('aW1hZ2U='),));$nvw_3d=array();$nvw_3d[base64_decode('cG9zdF9pZA==')]="$cpf_3b";$qye_3e=wp_count_comments($cpf_3b);$nvw_3d[base64_decode('Y29tbWVudHMtY291bnQ=')]=0;if($qye_3e){$nvw_3d[base64_decode('Y29tbWVudHMtY291bnQ=')]=intval($qye_3e->$npl_3f);}$nvw_3d[base64_decode('cGVybWFsaW5r')]=get_permalink($cpf_3b);if(strlen(trim(get_option(base64_decode('bWxfY3VzdG9tX2ZpZWxkX3VybA=='),'')))>0){$eqb_40=get_post_meta($sst_3a->$zmr_31,get_option(base64_decode('bWxfY3VzdG9tX2ZpZWxkX3VybA==')),true);if(strlen(trim($eqb_40))>0){$nvw_3d[base64_decode('cGVybWFsaW5r')]=$eqb_40;}}$nvw_3d[base64_decode('YXV0aG9y')]=array();$nvw_3d[base64_decode('YXV0aG9y')][base64_decode('bmFtZQ==')]=html_entity_decode(get_author_name($sst_3a->$xgt_41));$nvw_3d[base64_decode('YXV0aG9y')][base64_decode('YXV0aG9yX2lk')]=$sst_3a->$xgt_41;$nvw_3d[base64_decode('cG9zdF90eXBl')]=$sst_3a->$ndc_42;$nvw_3d[base64_decode('Y2F0ZWdvcmllcw==')]=array();$qac_43=get_the_category($cpf_3b);foreach($qac_43as $mpu_14){$nvw_3d[base64_decode('Y2F0ZWdvcmllcw==')][]=array(base64_decode('Y2F0X2lk') =>"$mpu_14->$rml_19",base64_decode('bmFtZQ==') =>$mpu_14->$kbn_25,base64_decode('c2x1Zw==') =>$mpu_14->$tqx_44);}$nvw_3d[base64_decode('dGl0bGU=')]=strip_tags($sst_3a->$bxs_45);if(get_option(base64_decode('bWxfZGF0ZXR5cGU='),base64_decode('cHJldHR5ZGF0ZQ=='))==base64_decode('ZGF0ZXRpbWU=')){$nvw_3d[base64_decode('ZGF0ZV9kaXNwbGF5')]=date_i18n(get_option(base64_decode('bWxfZGF0ZWZvcm1hdA=='),base64_decode('RiBqLCBZ')),strtotime($sst_3a->$sam_46),get_option(base64_decode('Z210X29mZnNldA==')));}$nvw_3d[base64_decode('ZGF0ZQ==')]=$sst_3a->$sam_46;if(get_option(base64_decode('bWxfZWFnZXJfbG9hZGluZ19lbmFibGU='))==true ||$tnp_39==base64_decode('dHJ1ZQ==') ||$wqe_47==base64_decode('cGFnZQ==') ||isset($_POST[base64_decode('cG9zdF9pZA==')])){}else{$nvw_3d[base64_decode('bGF6eQ==')]=base64_decode('dHJ1ZQ==');}try{$pdy_48=get_the_first_youtube_id($sst_3a);}catch(Exception $wvx_49){}try{//featured image
 $gpc_4a=get_the_first_image($sst_3a);}catch(Exception $wvx_49){//error getting or resizing the images
}$nvw_3d[base64_decode('dmlkZW9z')]=array();$nvw_3d[base64_decode('aW1hZ2Vz')]=array();if($pdy_48!=NULL){$nvw_3d[base64_decode('dmlkZW9z')][]=$pdy_48;}if($gpc_4a!=NULL){$ytv_4b=array(base64_decode('ZnVsbA==') =>$gpc_4a,base64_decode('dGh1bWI=') =>array(base64_decode('dXJs') =>$gpc_4a),base64_decode('YmlnLXRodW1i') =>array(base64_decode('dXJs') =>$gpc_4a));$nvw_3d[base64_decode('aW1hZ2Vz')][0]=$ytv_4b;}/* if(strlen(get_option('ml_custom_featured_image', '')) > 0) {
            $custom_featured_image_url = get_post_meta($post->ID, get_option('ml_custom_featured_image', ''), true);
            $final_post["images"][0] = array(
                "full" => $custom_featured_image_url, 
                "thumb" => array("url" => $custom_featured_image_url),
                "big-thumb" => array("url" => $custom_featured_image_url)
            );
        } */ if(strlen(get_option(base64_decode('bWxfY3VzdG9tX2ZlYXR1cmVkX2ltYWdl')))>0 &&class_exists(base64_decode('TXVsdGlQb3N0VGh1bWJuYWlscw=='))){$kjv_4c=MultiPostThumbnails::get_post_thumbnail_url(get_post_type($sst_3a->$zmr_31),Mobiloud::get_option(base64_decode('bWxfY3VzdG9tX2ZlYXR1cmVkX2ltYWdl')),$sst_3a->$zmr_31,base64_decode('bGFyZ2U='));if($kjv_4c!==false){$nvw_3d[base64_decode('aW1hZ2Vz')][0]=array(base64_decode('ZnVsbA==') =>$kjv_4c,base64_decode('dGh1bWI=') =>array(base64_decode('dXJs') =>$kjv_4c),base64_decode('YmlnLXRodW1i') =>array(base64_decode('dXJs') =>$kjv_4c));}}foreach((array)$acf_3cas $ytv_4b){$slm_4d=array();$slm_4d[base64_decode('ZnVsbA==')]=wp_get_attachment_image_src($ytv_4b->$zmr_31,base64_decode('ZnVsbA=='));$slm_4d[base64_decode('dGh1bWI=')]=wp_get_attachment_image_src($ytv_4b->$zmr_31,base64_decode('dGh1bWJuYWls'));$slm_4d[base64_decode('aW1hZ2VJZA==')]=$ytv_4b->$zmr_31;$nvw_3d[base64_decode('aW1hZ2Vz')][]=$slm_4d;}if($tnp_39){if(get_option(base64_decode('bWxfZWFnZXJfbG9hZGluZ19lbmFibGU='))==true){$nvw_3d[base64_decode('bGF6eQ==')]=base64_decode('dHJ1ZQ==');}else{$nvw_3d[base64_decode('bGF6eQ==')]=base64_decode('ZmFsc2U=');}}else{$nvw_3d[base64_decode('bGF6eQ==')]=base64_decode('ZmFsc2U=');}// if($final_post["lazy"] == 'true' || isset($_POST["post_id"])) {
 //capturing the html output generated
 ob_start();$hyf_4e=ob_get_clean();//replace relative URLs with absolute
 $hyf_4e=preg_replace(base64_decode('Iyg8cyphcytbXj5dKmhyZWZzKj1zKlsiJ10pKD8haHR0cHwvKShbXiInPl0rKShbIic+XSspIw=='),base64_decode('JDE=').$nvw_3d[base64_decode('cGVybWFsaW5r')].base64_decode('LyQyJDM='),$hyf_4e);$nvw_3d[base64_decode('Y29udGVudA==')]=$hyf_4e;// } else {
 //     $final_post['content'] = '';
 // }
 //sticky ?
 $nvw_3d[base64_decode('c3RpY2t5')]=is_sticky($sst_3a->$zmr_31)||$sst_3a->$syg_2e;//custom field?
 if(strlen(get_option(base64_decode('bWxfY3VzdG9tX2ZpZWxkX25hbWU='),''))>0){if(get_option(base64_decode('bWxfY3VzdG9tX2ZpZWxkX25hbWU='),'')==base64_decode('ZXhjZXJwdA==')){//              setup_postdata( $post->ID );
 $dqt_4f=html_entity_decode(urldecode(strip_tags(get_post_excerpt($sst_3a->$zmr_31))));//              $custom_field_val = preg_replace_callback("/(&#[0-9]+;)/", function($m) { return mb_convert_encoding($m[1], "UTF-8", "HTML-ENTITIES"); }, $custom_field_val); 
 $nvw_3d[base64_decode('Y3VzdG9tMQ==')]=$dqt_4f;}else{$dqt_4f=get_post_meta($sst_3a->$zmr_31,get_option(base64_decode('bWxfY3VzdG9tX2ZpZWxkX25hbWU='),''),true);$nvw_3d[base64_decode('Y3VzdG9tMQ==')]=$dqt_4f;}}//excerpt
 $nvw_3d[base64_decode('ZXhjZXJwdA==')]=html_entity_decode(urldecode(strip_tags(get_post_excerpt($sst_3a->$zmr_31))));$lrz_38[base64_decode('cG9zdHM=')][]=$nvw_3d;}// Add a top-level attribute for the taxonomy if we had a taxonomy permalink request
 if($hrw_0){$lrz_38[base64_decode('dGF4b25vbXk=')]=$zdk_8;}$nng_50=wp_get_current_user();$lrz_38=apply_filters(base64_decode('bWxfcG9zdHM='),$lrz_38,$nng_50);$wlc_51=json_encode($lrz_38);echo $wlc_51;//caching json string if is main posts
 if($oba_36==0){//ml_cache_set('main_posts',$json_string);
}}function get_post_excerpt($cpf_3b){global $sst_3a;$pko_52=$sst_3a;$sst_3a=get_post($cpf_3b);$xhn_53=get_the_excerpt();$sst_3a=$pko_52;return $xhn_53;}function get_the_first_image($sst_3a){//try to get the featured image
 if(has_post_thumbnail($sst_3a->$zmr_31)){$ytv_4b=wp_get_attachment_image_src(get_post_thumbnail_id($sst_3a->$zmr_31),base64_decode('ZnVsbA=='));if($ytv_4b!=NULL &&count($ytv_4b)>0){return $ytv_4b[0];}}//if there is no featured image, check what's the first image
 //inside the html.
 $eum_54=str_get_html($sst_3a->$qyq_55);if($eum_54==NULL)return NULL;$rps_56=$eum_54->find(base64_decode('aW1n'));foreach($rps_56as $lji_57){if($lji_57&&isset($lji_57->$ttn_58)){return $lji_57->$ttn_58;}}return NULL;}function get_first_attachment_url($cpf_3b){$kkf_59=array(base64_decode('cG9zdF90eXBl') =>base64_decode('YXR0YWNobWVudA=='),base64_decode('bnVtYmVycG9zdHM=') =>null,base64_decode('cG9zdF9zdGF0dXM=') =>null,base64_decode('cG9zdF9wYXJlbnQ=') =>$cpf_3b);$ncu_5a=get_posts($kkf_59);if($ncu_5a&&count($ncu_5a)>0){$ytl_5b=$ncu_5a[0];$ytv_4b=wp_get_attachment_image_src($ytl_5b->$zmr_31,base64_decode('ZnVsbA=='));if($ytv_4b&&count($ytv_4b)>0){$nai_5c=$ytv_4b[0];return $nai_5c;}}return NULL;}function get_the_first_youtube_id($sst_3a){$eum_54=str_get_html($sst_3a->$qyq_55);if($eum_54==NULL)return NULL;$tvu_5d=$eum_54->find(base64_decode('aWZyYW1l'));foreach($tvu_5das $fgs_30){$tun_5e=youtubeID_from_link($fgs_30->$ttn_58);if($tun_5e!=NULL)return $tun_5e;}return NULL;}function get_post_comment_count($cpf_3b){global $cdt_5f;$zfh_60="SELECT * FROM $cdt_5f->$lep_61 WHERE comment_post_ID=".$cpf_3b;$bpu_62=$cdt_5f->get_results($zfh_60);return count($bpu_62);}function get_post_count($qac_43){global $cdt_5f;$tfa_63=0;foreach($qac_43as $hki_24):$mdl_64="
                SELECT count
                FROM $cdt_5f->$hsv_65, $cdt_5f->$lco_66, $cdt_5f->$dms_67
                WHERE $cdt_5f->$lco_66.ID = $cdt_5f->$dms_67.object_id
                AND $cdt_5f->$dms_67.term_taxonomy_id = $cdt_5f->$hsv_65.term_taxonomy_id
                AND $cdt_5f->$hsv_65.term_id = $hki_24
                AND $cdt_5f->$lco_66.post_status = 'publish'
            ";$aua_68=$cdt_5f->get_var($mdl_64);$tfa_63+=$aua_68;endforeach;return $tfa_63;}function youtubeID_from_link($ywa_69){$gyk_6a=array();if(preg_match(base64_decode('fg0KICAgICAgICAjIE1hdGNoIG5vbi1saW5rZWQgeW91dHViZSBVUkwgaW4gdGhlIHdpbGQuIChSZXY6MjAxMTEwMTIpDQogICAgICAgIGh0dHBzPzovLyAgICAgICAgICMgUmVxdWlyZWQgc2NoZW1lLiBFaXRoZXIgaHR0cCBvciBodHRwcy4NCiAgICAgICAgKD86WzAtOUEtWi1dK1wuKT8gIyBPcHRpb25hbCBzdWJkb21haW4uDQogICAgICAgICg/OiAgICAgICAgICAgICAgICMgR3JvdXAgaG9zdCBhbHRlcm5hdGl2ZXMuDQogICAgICAgICAgeW91dHVcLmJlLyAgICAgICMgRWl0aGVyIHlvdXR1LmJlLA0KICAgICAgICB8IHlvdXR1YmVcLmNvbSAgICAjIG9yIHlvdXR1YmUuY29tIGZvbGxvd2VkIGJ5DQogICAgICAgICAgXFMqICAgICAgICAgICAgICMgQWxsb3cgYW55dGhpbmcgdXAgdG8gVklERU9fSUQsDQogICAgICAgICAgW15cd1wtXHNdICAgICAgICMgYnV0IGNoYXIgYmVmb3JlIElEIGlzIG5vbi1JRCBjaGFyLg0KICAgICAgICApICAgICAgICAgICAgICAgICAjIEVuZCBob3N0IGFsdGVybmF0aXZlcy4NCiAgICAgICAgKFtcd1wtXXsxMX0pICAgICAgIyAkMTogVklERU9fSUQgaXMgZXhhY3RseSAxMSBjaGFycy4NCiAgICAgICAgKD89W15cd1wtXXwkKSAgICAgIyBBc3NlcnQgbmV4dCBjaGFyIGlzIG5vbi1JRCBvciBFT1MuDQogICAgICAgICg/ISAgICAgICAgICAgICAgICMgQXNzZXJ0IFVSTCBpcyBub3QgcHJlLWxpbmtlZC4NCiAgICAgICAgICBbPz0mKyVcd10qICAgICAgIyBBbGxvdyBVUkwgKHF1ZXJ5KSByZW1haW5kZXIuDQogICAgICAgICAgKD86ICAgICAgICAgICAgICMgR3JvdXAgcHJlLWxpbmtlZCBhbHRlcm5hdGl2ZXMuDQogICAgICAgICAgICBbXCciXVtePD5dKj4gICMgRWl0aGVyIGluc2lkZSBhIHN0YXJ0IHRhZywNCiAgICAgICAgICB8IDwvYT4gICAgICAgICAgIyBvciBpbnNpZGUgPGE+IGVsZW1lbnQgdGV4dCBjb250ZW50cy4NCiAgICAgICAgICApICAgICAgICAgICAgICAgIyBFbmQgcmVjb2duaXplZCBwcmUtbGlua2VkIGFsdHMuDQogICAgICAgICkgICAgICAgICAgICAgICAgICMgRW5kIG5lZ2F0aXZlIGxvb2thaGVhZCBhc3NlcnRpb24uDQogICAgICAgIFs/PSYrJVx3LV0qICAgICAgICAjIENvbnN1bWUgYW55IFVSTCAocXVlcnkpIHJlbWFpbmRlci4NCiAgICAgICAgfml4'),$ywa_69,$gyk_6a)){if(count($gyk_6a)>=2){return $gyk_6a[1];}}else return NULL;}function ml_get_term_by($ymf_6b,$qzz_6c){$ztn_6d=ml_get_used_taxonomies();foreach($ztn_6das $hka_6e){$dzi_6f=get_term_by($ymf_6b,$qzz_6c,$hka_6e);if($dzi_6f){return array(base64_decode('dGVybQ==') =>$dzi_6f,base64_decode('dGF4') =>$hka_6e);}}return array(base64_decode('dGVybQ==') =>false,base64_decode('dGF4') =>false);}function ml_get_used_taxonomies(){$ztn_6d=array(base64_decode('Y2F0ZWdvcnk='),base64_decode('cG9zdF90YWc='));$uip_70=get_option(base64_decode('bWxfbWVudV90ZXJtcw=='),array());foreach($uip_70as $dzi_6f){$vph_71=explode(base64_decode('PQ=='),$dzi_6f);$ztn_6d[]=$vph_71[0];}return $ztn_6d;}function ml_get_category_child_post_count($hgs_72,$zdk_8=base64_decode('Y2F0ZWdvcnk=')){$ycy_73=0;$ysa_74=get_terms($zdk_8,array(base64_decode('Y2hpbGRfb2Y=') =>$hgs_72));foreach($ysa_74as $hoe_75){$ycy_73+=$hoe_75->$skq_76;}return $ycy_73;}?>